version: '3.8'

services:
  db:
    image: postgres:14.18
    container_name: siemens-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - siemens-net
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: abdulshafi/siemens-initial-project:v2
    container_name: siemens-app
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://siemens-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - siemens-net

networks:
  siemens-net:
    driver: bridge

volumes:
  db_data:
